### PR TITLE
Moved loot arround Update config.cpp

### PR DESCRIPTION
**Pull request by nerdalertdk**
Removed none exile stuff plus moved to items

### CODE REVIEW

**Comment by KawaiiPotato** [comment]
You might want to hold off on the non-mission critical pull requests, IT07 said he has to merge them manually and he doesn't like to do it because its a pain.

**Comment by IT07** [comment]
Not sure if I already mentioned it, but I am kind of offended by this. It just feels like that for some reason. Sorry if I am offending you with this but please; mind your own business you're not a scarCODE developer so why do all these changes? If you have a request you can pm me or something ok? But please not like this.

**Comment by nerdalertdk** [comment]
what fork and pulls is what github is about ?

**Comment by IT07** [comment]
A private git requires a paid account. I think I invest enough in developing by taking my free time to do this. And private means it is not accessible, right?

**Comment by KawaiiPotato** [comment]
Go into the settings and turn on Restrict editing to collaborators only if you want it accessible but without editing.

**Comment by nerdalertdk** [comment]
And why are you offended by such a small change ?
I merely removed items that are not in the core exile game like mine detector and medkits, it's not like are rewrote core function or said it had to be done by tomorrow?

**Comment by IT07** [comment]
It is not your fault mate. I just do not like it when people "correct" me. I am not saying that you are correcting me I am just saying that my past has a lot of those kind of people in it so I am very sensitive to that. Sorry

**Pull request closed without merging**
